version: '3'
services:
  marblecutter:
    build: .
    environment:
      - PYTHONPATH=.
      - GDAL_DISABLE_READDIR_ON_OPEN=YES
      - CPL_VSIL_CURL_ALLOWED_EXTENSIONS=.tif

    volumes:
      - .:/opt/marblecutter/
    ports:
      - "8000:8000"
    restart: unless-stopped
    entrypoint: python
    command: server.py
