version: '3'
services:
    marblecutter:
        build: .
        networks:
            - tiler
        environment:
            - PYTHONPATH=.
            - GDAL_DISABLE_READDIR_ON_OPEN=YES
            - CPL_VSIL_CURL_ALLOWED_EXTENSIONS=.tif
            - VSI_CACHE_SIZE=536870912 # tune to available RAM
            - WEB_CONCURRENCY=4        # tune to 2-4x $(nproc)
            - FLASK_PROXY_DEPTH=2      # 1 if using nginx, 2 if using varnish+nginx
        platform: linux/amd64
          # volumes:
          #   - .:/opt/marblecutter/
        # ports:
        #   - "8085:8085"
        restart: unless-stopped
        entrypoint: "poetry"
        command: "run gunicorn -w 8 server:app"
    varnish:
        image: varnish:alpine
        environment:
            - VARNISH_SIZE=2G
        networks:
            - tiler
        depends_on:
            - marblecutter
        container_name: varnish
        volumes:
          - "./varnish/default.vcl:/etc/varnish/default.vcl"
        ports:
          - "6082:80"
        environment:
          - VARNISH_SIZE=2G  
        command: "-p default_keep=300"
networks:
    tiler:

