version: '3'
services:

  marblecutter:
    build: .
    environment:
      - PYTHONPATH=.
    volumes:
      - .:/opt/marblecutter/
    restart: unless-stopped

  caddy:
    image: caddy:2.1.1-alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    command: caddy reverse-proxy --from ${DOMAIN} --to marblecutter:8000
