version: '3'
services:
  marblecutter:
    build: .
    environment:
      - PYTHONPATH=.
      - GDAL_DISABLE_READDIR_ON_OPEN=YES
      - CPL_VSIL_CURL_ALLOWED_EXTENSIONS=.tif
    platform: linux/amd64
    # volumes:
    #   - .:/opt/marblecutter/
    ports:
      - "8085:8085"
    restart: unless-stopped
    entrypoint: "poetry"
    command: "run gunicorn -w 8 server.py"
